#import string
#KHE:Grue
#things to do
# generate maze
# design maze? pen and paper this
# recognize location: recognize the available rooms/movement
# show actions/help
# actions and options
# interactions
# lvl/scaling/etc
# win conditions?

#setup all the variables
items = {}
done = False
inventory = ['pocketlint']
verbose = {}

location = 0
#location = 9

movement = ["n", "north", "e", "east", "s", "south", "w", "west", "up", "u", "down", "d"]
extras = ["look", "verbose", "inventory", "help", "quit"]
movescount = 0
movesfail = 0
points = 0
score = 0


def intro():
	print("------------------------------------------------------")
	print("""PyZork - KHE 2017 - Brian Kost (YSU)
*not affiliated with pyzorkprofessor.com in any fashion,
other than the same first six letters*

Fire up an AAA game nowadays and you have all of the output regarding
things directly in front of you, in up to 4k+ HD Splendor.

Sounds: be they vocal, atmospheric, backgound, or foley
come at you in your high definition delivery system of choice.

PyZork is NOT one of those games.

PyZork spiritual anscestor/inspiration for is the original Zork,
 - Zork: The Great Underground Empire - Part I. (https://en.wikipedia.org/wiki/Zork)

Effectively a labyrinthian dungeon crawl, where the only feedback the player recieved was in text form,
as a direct response to --whatever the player told the game to do...
 - Thus, no shiny sparkes to draw your attention to an object.
 - No on screen maps.
 - No radar/sonar/psychic-warning-device that misfortune was right around the corner.

This genre is before the advent of hex/grid based adventure games also, so a player could
effectively leave a zone through the east/west side and enter the NEXT zone from the east/west
side.

Can't happen, you say?

Well, draw a circle and a square and a triangle. Now draw a line
from the right side of one to the right side to another.

The shortest distance between two points IS a straight line, but look at a map
(or google map/directions) and find the path between Columbus, OH, USA and
Toronto, ON, Canada. Driving in a straight line just puts another car in Lake Erie.

So, forget all of the assumptions and established tropes generated by the 40 years of computer gaming
since 1977, and get a taste of the glory of text based adventure games.""")
	print("------------------------------------------------------")
	print("Advisement:")
	print("""The similarities to Zork are in spirit and in style,
based only on personal familiarity with playing the game and series.
In no manner or fashion was any code found, utilized, or reverse
engineered from any of the Zork Products, Entities, or IP.""")
	print("------------------------------------------------------")
	print("\n")
	print("Oh, and here's your one and only hint:")
	print("	If you're unfamiliar with this style")
	print("	of game... by all means, please,")
	print("	have your first action be: HELP")
	print("								Brian K")
	print("------------------------------------------------------")
	print("\n")
	return()

def endgame(movescount, movesfail, score, points):
	movescount *= 1.00
	movesfail *= 1.00
	rating = (movescount/(movesfail+movescount))
	print("\n")
	print("Thank you for playing PyZork...")
	print("Effective actions:", movescount)
	print("Ineffective actions:",movesfail)
	print("Rating: ", ((rating)*100),'%')
	print("Score: ", points, "(out of possible", score, ")")
	print(score, rating)
	print("Effective Score: ", (points*rating) )


	return (movescount, movesfail, score, points)


def actions(world, verbose, location, movement, extras, inventory, items, movescount, movesfail, points):
	words = ""
	wordlist = []
	wordcount = 0
	done = False
	dothis = input('>>> ').lower()
	words = dothis.split(" ")
	
	#find the keywords-Actions--------------------
	for num in range (0, len(words)):

		if words[num] in movement or words[num] in extras or words[num] in inventory or (words[num] in world[location]["special"]):
			wordcount += 1
			wordlist.append(words[num])
			
	
	if wordcount >= 2:
		print('You want to ', wordlist[0].upper(), 'with the',\
		 wordlist[1].upper()+'? I am but your humble guide... and easily confused.')
		print('Hint: you might be combining multiple actions')
		movesfail += 1
		return (location, inventory, done, movescount, movesfail, points)
	#elif wordcount == 1:
	#	wordlist[0] = words[0]
	#	print(wordcount) #trying this
	elif wordcount == 0:
		print("I didn't quite catch that. What?")
		movesfail += 1
		return (location, inventory, done, movescount, movesfail, points)

	
	#wordlist-movement--------------------
	if wordlist[0] in movement:
		if wordlist[0][0] == "n" and (world[location]['n'] >= 0):
			location = int(world[location]['n'])
			movescount += 1
			#print(location)
			
		elif wordlist[0][0] == "e" and (world[location]['e'] >= 0):
			movescount += 1
			location = int(world[location]['e'])
			#print(location)

		elif wordlist[0][0] == "s" and (world[location]['s'] >= 0):
			movescount += 1
			location = int(world[location]['s'])
			#print(location)

		elif wordlist[0][0] == "w" and (world[location]['w'] >= 0):
			movescount += 1
			location = int(world[location]['w'])
			#print(location)

		elif wordlist[0][0] == "u" and (world[location]['u'] >= 0):
			movescount += 1
			location = int(world[location]['u'])
			#print(location)

		elif wordlist[0][0] == "d" and (world[location]['d'] >= 0):
			movescount += 1
			location = int(world[location]['d'])
			#print(location)

		else:
			movesfail += 1

		print(verbose[location]['short'])
	
	#wordlist-extras--------------------
	elif wordlist[0] in extras:
		movescount += 1
		if wordlist[0] == "quit":
			done = True
		if wordlist[0] == "inventory":
			print("\nYou are carrying:")
			for num in range(0,len(inventory)):
				if inventory[num] == "":
					inventory.remove("")
				else:
					print(inventory[num].capitalize())

		if wordlist[0] == "look":
			print("\n",verbose[location]["long"])
			print("\nYou see:", world[location]["special"])
			print ('\nYou think you should be able to travel: ')
			if world[location]['n'] >= 0:
				print ('North')
			if world[location]['e'] >= 0:
				print ('East')
			if world[location]['s'] >= 0:
				print ('South')
			if world[location]['w'] >= 0:
				print ('West')
			if world[location]['u'] >= 0:
				print ('Up')
			if world[location]['d'] >= 0:
				print ('Down')

		if wordlist[0] == "help":
			print("\n")
			print("Once upon a time, grand stories were told without pictures...")
			print("...and sometimes even without instructions.")
			print("\n")
			print("'n', 'north', 'e', 'east', 's', 'south', 'w', 'west' will start getting you around...")
			print("'Inventory' will let you know what you have in your pockets.")
			print("For more detail... take a 'look'.")
			print("...and for those who would rather go find a world of pictures and graphics, 'quit' will start that journey.")
			print("\n")

	#special/pickup
	elif world[location]["special"].lower() in dothis.lower(): 
		movescount += 1
		print(world[location]["interactions"])
		if world[location]["loot"] != "none":
			inventory.insert (0, world[location]["loot"])
			world[location]["loot"] = "none"
			world[location]["special"] = ""
			points += world[location]["points"]
			world[location]["points"] = 0
			print('\nYou are now carrying:')
			for num in range (0,len(inventory)):
				print(inventory[num].capitalize())

# LOCATION EXCEPTIONS----------------------------------------

	if location == 2 and 'woodenstake' in inventory and wordlist[0].lower() == 'woodenstake':
		print("Even though the ground at the cliff edge is frightening,", 
			"\na little further back you can spike the wooden stake securely into the ground.\n",
			"Once that is secure, the rope across the chasm is easy to secure as well.")
		inventory.remove('woodenstake');
		world[2]['e'] = 3
		world[2]['interactions'] = "You feel confidant that you will be able to make it to the other side now, even if you have to basically hang upside down to do so."
		print('woodenstake: removed from inventory')
		points += 5
		movescount += 1
		return (location,inventory,done, movescount, movesfail, points)

	elif location == 13 and 'obsidian' in inventory and 'turquoise' in inventory and 'quartz' in inventory \
		and (wordlist[0].lower() == 'quartz' or wordlist[0].lower() =='turquoise' or wordlist[0].lower() == 'obsidian'):

		inventory.remove('turquoise');
		inventory.remove('quartz');
		inventory.remove('obsidian');

		print('\n')
		print('Turquoise: removed from inventory')
		print('Quartz: removed from inventory')
		print('Obsidian: removed from inventory')
		print('\n')

		points += 10

		movescount += 1

		print("""Whether it was a natural aptitude for the arts, a sense of feng shui, or dumb luck...
The gemstones fit into some of the deeper marks on the heiroglyphics.
With a small shudder and shake (which makes you glance up at any overhanging
rocks), the rockface slides open like a panel... giving you admittance to the depths.""")

		verbose[13] = {"short":"...Climbing Down...",
	"long":
"""Where once was a rock face with heiroglyphics, now rests a rock door ajar.""",
"interactions":"If you peer around the now open stone door, you can see the carvings and the gems inlaid in their sockets... however it is impossible to reach or remove the gems from their new home."}

		world[13]['n'] = 14
		return (location, inventory, done, movescount, movesfail, points)

	elif location == 14 and wordlist[0].lower() == 'torch':
		print("""As you heft the torch up and out of its sconce on the wall,
you no longer think that devling into the dark is a bad idea.""")
		world[14]['d'] = 19
		return (location, inventory, done, movescount, movesfail, points)

	elif location == 30 and wordlist[0].lower() == 'pocketlint':
		print("""The giant of a man recieves his toll with outstretched hand and steps aside.""")
		world[30]['n']=37
		inventory.remove('pocketlint');
		inventory += ('diamonddust')
		movescount +=1
		points += 10
		return (location, inventory, done, movescount, movesfail, points)

	elif location == 60 and wordlist[0].lower() == 'key':
		print("""Somehow, the key turns smoothly in the lock... only to break when you try to remove it.""")
		world[39]['e']=40
		inventory.remove('ley');
		movescount +=1
		points += 10
		return (location, inventory, done, movescount, movesfail, points)

	elif wordlist[0].lower() in inventory:
		print (items[wordlist[0]])
		movescount += 1
		return (location, inventory, done, movescount, movesfail, points)


	return(location, inventory, done, movescount, movesfail, points)


#WORLD BUILDING----------------------------------------

world = {}
world[0] = {"loc" : 0,"desc": 0,
		"n":-1, "e":1, "s":1, "w":-1, "u": -1, "d": -1,
		"special": "mailbox",
		"interactions":"You pick up a weathered letter that is somewhat legible even through the water stains.",
		"loot": "letter",
		"points": 1
		}
world[1] = {"loc" : 1,"desc": 1,
		"n":0, "e":-1, "s":0, "w":2, "u": -1, "d": -1,
		"special": "fire",
		"interactions":"As out of place as the scorch mark is, all you find is a charred piece of wood - burnt to a point.",
		"loot": "woodenstake",
		"points": 3
		}
world[2] = {"loc" : 2,"desc": 2,
		"n":1, "e":-1, "s":-1, "w":-1, "u": -1, "d": -1,
		"special": "bridge",
		"interactions":"Upon closer inspection, a rope is still firmly attached on the other side. However, it is basically unsecured on your face of the cliff.",
		"loot": "none",
		"points": 0
		}		
world[3] = {"loc" : 3,"desc": 3,
		"n":-1, "e":4, "s":-1, "w":-1, "u": -1, "d": -1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[4] = {"loc" : 4,"desc": 4, "u": -1, "d": -1,
		"n":-1, "e":5, "s":-1, "w":-1,
		"special": "bridge",
		"interactions":"It's not a bullwhip, but having some rope just feels useful. You coil the rope until it breaks at a weatherworn spot and throw that coil over a shoulder",
		"loot": "rope",
		"points": 2
		}		

# NEW ROOMS

world[5] = {"loc" : 5,"desc": 5, "u": -1, "d": -1,
		"n":-1, "e":6, "s":-1, "w":4,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		
world[6] = {"loc" : 6,"desc": 6, "u": -1, "d": -1,
		"n":7, "e":9, "s":8, "w":5,
		"special": "tree",
		"interactions":"The grand oak tree just seems put there to be climbed, perhaps it is but a memory of your childhood? Nonetheless, there are no good handholds or footholds to give purchase for a climb.",
		"loot": "none",
		"points": 0
		}		
world[7] = {"loc" : 7,"desc": 7, "u": -1, "d": -1,
		"n":-1, "e":9, "s":-1, "w":6,
		"special": "tree",
		"interactions":"Upon close inspection, the tree is dead and barren. The have been no apples here for a long time.",
		"loot": "none",
		"points": 0
		}		
world[8] = {"loc" : 8,"desc": 8, "u": -1, "d": -1,
		"n":-1, "e":9, "s":-1, "w":6,
		"special": "tree",
		"interactions":"The trunk has been gnawed and clawed by various beasts claming this land as their own.",
		"loot": "pinecone",
		"points": 1
		}		
world[9] = {"loc" : 9,"desc": 9, "u": -1, "d": 10,
		"n":7, "e":-1, "s":8, "w":6,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		

#WORLD --10 and up--

world[10] = {"loc" : 10,"desc": 10, "u": 9, "d": 11,
		"n":-1, "e":-1, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		
world[11] = {"loc" : 11,"desc": 11, "u": 10, "d": 13,
		"n":12, "e":-1, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		
world[12] = {"loc" : 12,"desc": 12, "u": -1, "d": -1,
		"n":11, "e":-1, "s":-1, "w":-1,
		"special": "geode",
		"interactions":"While looking at the intricate work of nature, you inadvertantly break off a chunk of crystal. Since you cannot put it back, might as well put it in your pocket.",
		"loot": "quartz",
		"points": 2
		}		
world[13] = {"loc" : 13,"desc": 13, "u": 11, "d": 15,
		"n":-1, "e":-1, "s":-1, "w":-1,
		"special": "heiroglyphics",
		"interactions":"The rock face has some rather intricate, yet worn, carvings. Call me strange, but it feels like the pattern is missing something... \nYou can make out three indentations that just seem out of place in the rock face.",
		"loot": "none",
		"points": 0
		}		
world[14] = {"loc" : 14,"desc": 14, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":13, "w":-1,
		"special": "torch",
		"interactions":"Considering that you're all but underground - only reflections of sunlight are guiding your way currently - a lit torch is not a bad idea.",
		"loot": "torch",
		"points": 0
		}		
world[15] = {"loc" : 15,"desc": 15, "u": 13, "d": 17,
		"n":-1, "e":-1, "s":16, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		
world[16] = {"loc" : 16,"desc": 16, "u": -1, "d": -1,
		"n":15, "e":-1, "s":-1, "w":-1,
		"special": "nest",
		"interactions":"The birds nest has the look of age: dust and cobwebs have gone undisturbed for untold amounts of time. However, a sliver or turquoise catches your eye. Your pockets catch the turquoise immediately after",
		"loot": "turquoise",
		"points": 2
		}		
world[17] = {"loc" : 17,"desc": 17, "u": 15, "d": 18,
		"n":-1, "e":-1, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		
world[18] = {"loc" : 18,"desc": 18, "u": 17, "d": -1,
		"n":-1, "e":-1, "s":-1, "w":-1,
		"special": "shard",
		"interactions":"While adjusting your balance to try to find the shine you once glimpsed, the rock face breaks underhand. A piece of pure obsidian falls beside you, catching the light in its own eerie manner.",
		"loot": "obsidian",
		"points": 2
		}		
world[19] = {"loc" : 19,"desc": 19, "u": -1, "d": -1,
		"n":20, "e":-1, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		
world[20] = {"loc" : 20,"desc": 20, "u": -1, "d": -1,
		"n":24, "e":22, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}		

#world --21-- and up

world[21] = {"loc" : 21,"desc": 21, "u": -1, "d": -1,
		"n":28, "e":-1, "s":27, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[22] = {"loc" : 22,"desc": 22, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":-1, "w":26,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[23] = {"loc" : 23,"desc": 23, "u": -1, "d": -1,
		"n":-1, "e":25, "s":27, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[24] = {"loc" : 24,"desc": 24, "u": -1, "d": -1,
		"n":-1, "e":22, "s":20, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[25] = {"loc" : 25,"desc": 25, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":20, "w":23,
		"special": "goldenbar",
		"interactions":"A golden bar. Here. A honest to something golden bar. Finder's keepers!",
		"loot": "goldbar",
		"points": 5
		}
world[26] = {"loc" : 26,"desc": 26, "u": -1, "d": -1,
		"n":21, "e":22, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[27] = {"loc" : 27,"desc": 27, "u": -1, "d": -1,
		"n":21, "e":-1, "s":-1, "w":23,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[28] = {"loc" : 28,"desc": 28, "u": -1, "d": -1,
		"n":29, "e":-1, "s":21, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[29] = {"loc" : 29,"desc": 29, "u": -1, "d": -1,
		"n":30, "e":-1, "s":28, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[30] = {"loc" : 30,"desc": 30, "u": -1, "d": -1,
		"n":-1, "e":34, "s":-1, "w":31,
		"special": "greenman",
		"interactions":"""The man (more a giant)... silent, stoic, tall, and probably stronger than a couple oxen stands mid-ford.
His pose may be relaxed, but his gaze easily communicates that there shall be no passing.
His voice bellows, and echoes down both directions of the chasm:
	'I am done with trading axeblows,
	'I tire of petty games with kings,
	'I challenge you to give me something
	
	'Pay me nothing with something...
	'...and consider the toll satisfied.'

	'Just remember:
	'Something of neither functional nor monetary value whatsoever.'""",
		"loot": "none",
		"points": 0
		}

#world --41-- and up

world[31] = {"loc" : 31,"desc": 31, "u": -1, "d": -1,
		"n":-1, "e":30, "s":-1, "w":32,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[32] = {"loc" : 32,"desc": 32, "u": -1, "d": -1,
		"n":-1, "e":31, "s":-1, "w":33,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[33] = {"loc" : 33,"desc": 33, "u": -1, "d": -1,
		"n":-1, "e":32, "s":-1, "w":33,
		"special": "clam",
		"interactions":"Well, maybe it was a trick of the light or refraction of the water, but it's not THAT big... tossing it down to the rocks in disappointment actually breaks the shell. (ooops)",
		"loot": "pearl",
		"points": 2
		}
world[34] = {"loc" : 34,"desc": 34, "u": -1, "d": -1,
		"n":-1, "e":35, "s":-1, "w":33,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[35] = {"loc" : 35,"desc": 35, "u": -1, "d": -1,
		"n":-1, "e":36, "s":-1, "w":34,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[36] = {"loc" : 36,"desc": 36, "u": -1, "d": -1,
		"n":-1, "e":36, "s":-1, "w":35,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[37] = {"loc" : 37,"desc": 37, "u": -1, "d": -1,
		"n":38, "e":-1, "s":30, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}

#final section 38-61 (omfg)

world[38] = {"loc" : 38,"desc": 38, "u": -1, "d": -1,
		"n":39, "e":-1, "s":37, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}

world[39] = {"loc" : 39,"desc": 39, "u": -1, "d": -1,
		"n":45, "e":-1, "s":38, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}

world[40] = {"loc" : 40,"desc": 40, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":-1, "w":39,
		"special": "skeleton",
		"interactions":"And upon that bare skeleton rests the holy Crown, glittering yet even now.",
		"loot": "crown",
		"points": 10
		}
world[41] = {"loc" : 41,"desc": 41, "u": -1, "d": -1,
		"n":-1, "e":42, "s":49, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[42] = {"loc" : 42,"desc": 42, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":46, "w":41,
		"special": "scraps",
		"interactions":"As you shuffle across the room, trying to not trip over anything underneath, you hear a faint mettalic sound. Moments later, an iron key is discovered.",
		"loot": "key",
		"points": 0
		}
world[43] = {"loc" : 43,"desc": 43, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":47, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[44] = {"loc" : 44,"desc": 44, "u": -1, "d": -1,
		"n":-1, "e":45, "s":48, "w":43,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[45] = {"loc" : 45,"desc": 45, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":44, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[46] = {"loc" : 46,"desc": 46, "u": -1, "d": -1,
		"n":-1, "e":47, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[47] = {"loc" : 47,"desc": 47, "u": -1, "d": -1,
		"n":-1, "e":48, "s":51, "w":46,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[48] = {"loc" : 48,"desc": 48, "u": -1, "d": -1,
		"n":44, "e":-1, "s":52, "w":47,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[49] = {"loc" : 49,"desc": 49, "u": -1, "d": -1,
		"n":41, "e":-1, "s":53, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[50] = {"loc" : 50,"desc": 50, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":49, "w":-1,
		"special": "flagstone",
		"interactions":"For as well as the floor had been worn, this piece of flagstone had been placed and removed numerous times.",
		"loot": "chalice",
		"points": 2
		}
world[51] = {"loc" : 51,"desc": 51, "u": -1, "d": -1,
		"n":-1, "e":52, "s":-1, "w":-1,
		"special": "coin",
		"interactions":"A single silver coin. Apparently this is your consolation prize.",
		"loot": "none",
		"points": 1
		}
world[52] = {"loc" : 52,"desc": 52, "u": -1, "d": -1,
		"n":-1, "e":-1, "s":56, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[53] = {"loc" : 53,"desc": 53, "u": -1, "d": -1,
		"n":49, "e":57, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[54] = {"loc" : 54,"desc": 54, "u": -1, "d": -1,
		"n":-1, "e":55, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[55] = {"loc" : 55,"desc": 55, "u": -1, "d": -1,
		"n":50, "e":-1, "s":-1, "w":54,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[56] = {"loc" : 56,"desc": 56, "u": -1, "d": -1,
		"n":52, "e":-1, "s":-1, "w":55,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[57] = {"loc" : 57,"desc": 57, "u": -1, "d": -1,
		"n":54, "e":58, "s":-1, "w":53,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[58] = {"loc" : 58,"desc": 58, "u": -1, "d": -1,
		"n":55, "e":59, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[59] = {"loc" : 59,"desc": 59, "u": -1, "d": -1,
		"n":56, "e":-1, "s":58, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}
world[60] = {"loc" : 60,"desc": 60, "u": -1, "d": -1,
		"n":39, "e":-1, "s":-1, "w":-1,
		"special": "keyhole",
		"interactions":"A keyhole. Isn't that blatantly obvious. Did we find a key?",
		"loot": "none",
		"points": 0
		}
world[61] = {"loc" : 61,"desc": 61, "u": 0, "d": -1,
		"n":-1, "e":-1, "s":-1, "w":-1,
		"special": "",
		"interactions":"",
		"loot": "none",
		"points": 0
		}

#the verbose area descriptions

verbose[0] = {"short":"You are standing near a derelict house.\n",
		"long":
'''You are standing outside what might had once
been a grand house... before a fire and nature reclaimed it.
Even the most cursory of glances prove without a shadow
of a doubt... that door is not going to open.
However, the house looks vaguely familiar.
At closer inspection you realize there is a busted mailbox
at your feet, hidden in the overgrowth which might had been
a lawn once. A dense forest wraps engulfs the house, and you
can barely make out what might be the sound of a river to the
east over the sounds of thick wilderness.'''
		}
verbose[1] = {"short":"You are standing in the middle of a thick forest.\n",
		"long":
'''The civilized world is but a memory here,
the forest having enveloped anything which may
have been here in the past. You can barely make
out what may be a few paths worn down by local
fauna... and some look questionable about being
able to return back through. Strangely enough, there
does seem to be the remnants of a very small fire
a few yards away even though you can barely see
the sky through the dense overhead canopy.'''
		}

verbose[2] = {"short":"You are standing alongside a rocky cliff.\n",
		"long":
'''Having finally extricated yoursef from the seeming
riotous growth of trees and woodland, you find yourself
overlooking a steep cliff. Any bit of curiosity you may
have felt regarding the edge is rapidly extinguished as
you realize that stepping to the precipice would most likely
result in the sun baked soil losing its tenuous fight
between gravity and friction. A dilapidated rope bridge
hangs down off the edge, dancing lightly in the breeze,
awaiting the inevitable plunge into what sounds like
a white water rafter's dream.'''
		}

verbose[3] = {"short":"...Hanging precariously over a deep chasm...",
		"long":
"""If it is any consolation, the rope you are hanging from seems
solid yet supple even after the untold years out in the unforgiving
weather. Glancing back at the western cliff edge, it looks like
the fight between gravity and friction is starting to show a favorable
leaning towards the powers of gravity - rocks and topsoil are now
freely falling into the abyss below - making a return to that side highly
questionable. You are sure that you'll be able to reach the eastern
side of the chasm. What that will gain you is yet to be seen."""
		}

verbose[4] = {"short":"Another cliff edge. Seemingly more stable.",
		"long":
"""You've gotten this far, and the past is behind you - literally. Just
like in life, there is no going back to the past (and the western side of
the chasm). The remnants of your makeshift passage are your only reminder
of your successful gravity defying escapade. The remnants of the rope
bridge you were able to see from the other side look even more dilapidated
now that you are in close proximity."""
		}

verbose[5] = {"short":"A small rise between hills.",
		"long":
"""It's quite the spectacular view, being on a small path between larger hills.
Well, a hill and what seems to be the mother of all hills to your East. However,
considering that some short time ago you hung suspended over roiling rapids hundreds
of feet ago - walking an incline seems to be nothing in comparison.

(To be honest, even I -your most humble guide- am still trying to not think about
those heights... eeep.)""" 
		}

verbose[6] = {
	"short":"Under the shade of an old oak tree.",
	"long":
"""A majestic oak tree raises its branches to the sky, offering you your first
bit of shade since the forest earlier. Considering the obscene overgrowth around
said forest, looking over the hills and at the nearby mountain - a fleeting sense
of serenty actually manages to catch hold. Enjoy it while it lasts."""

		}

verbose[7] = {
	"short":"Beside a dead and barren apple tree.",
	"long":
"""Distubing. It's the only word that comes to mind with the stark contrast of
what must have been a grandiose and fruit-laden tree at some point in the past.
You see no rot, so sign of lightning strikes, no visible damage from any local
fauna.

And with this massive expression of death in center frame before a serene natural
skyline... a slight chill crosses your back. Blame the breeze if you wish, but
the lifeless and unmoving branches decry that little white lie."""

		}

verbose[8] = {
	"short":"Near a rather grand pine tree.",
	"long":
"""Along the path, a pine tree strikes your attention. Some of the branches are gnarled,
the trunk appears to had been split once (or twice) in the past by lightning strikes.
However, this tree seems to be a case study in preserverence - still growing and green
in the face of nature's fickle adversity."""

		}

verbose[9] = {
	"short":"Might as well call it Lookout Point?",
	"long":
"""Wow.
Seriously.
You can see for miles in the crisp air from the crest of the mountain. As you scan the
horizon, you see no signs of life other than grasses and trees - the overgrown house in
woods is invisible - merely a memory.

Checking the ledge (which makes since considering your last trial against heights),
the drop is steep, but quite possibly manageable.

(or so you hope...)"""

		}

verbose[10] = {
	"short":"...Climbing Down...",
	"long":
"""Fortunately, appearances were correct: it is a managable climb - in both directions.
However, outside of scanning between the plentiful handholds and footholds, nothing much
is worthy of drawing your attention."""

		}

verbose[11] = {
	"short":"...Climbing Down...",
	"long":
"""Sometimes it's worth celebrating the small victories, the path up and down is still
managable and servicable. The handholds and footholds continue to be numerous... and to the
side there looks to be a rock outcropping you can walk to and get a different vantage
point."""

		}

verbose[12] = {
	"short":"The edge of an outcropping.",
	"long":
"""First opinion? The path you had been originally travelling vertically looks a whole
lot better when you're actually on it.
Second opinion? Don't develop a fear of heights.

Trying to avoid looking straight down into the chasm, peeing out between some randomly
strewn rocks appear to be a partially exposed geode."""

		}

verbose[13] = {
	"short":"...Climbing Down...",
	"long":
"""Well, THIS was unexpected. Your handholds and footholds, albeit a little more sparse
than earlier, are still available for travel. However while needing to take longer to secure
your grip, you realize there is an ornate carved set of heiroglyphics and runes etched into
the rock face directly in front of you."""

		}

verbose[14] = {
	"short":"Hand-carved passage.",
	"long":
"""Crudely hewn, this passage goes deeper yet into the side of the mountain. However, after
a certain point no external light actually penetrates the darkness within."""

		}

verbose[15] = {
	"short":"...Climbing Down...",
	"long":
"""How deep IS this thing?

At least up and down doesn't seem to be an issue anytime soon. After scanning the area,
it looks like there may be an alternate route here you can take."""

		}

verbose[16] = {
	"short":"...Climbing Down...",
	"long":
"""While maneuvering yourself across what you are now admitting to be a cliff face,
you catch yourself before putting your hand into an old birds nest... nestled and
undisturbed amongst the rocks for an untold age."""

		}

verbose[17] = {
	"short":"...Climbing Down...",
	"long":
"""Between the maneuvering and climbing, you can no longer see the point where
you initially started your descent down from Lookout Point. Much more further down and
you fear there may be no further progress. However a glint from the rocks under you,
similar to a reflection of sunlight off of glass draws your attention."""

		}

verbose[18] = {
	"short":"...the edge of the Abyss...",
	"long":
"""Somewhere between the points of 'mountain' and 'treacherous climb' you notice a
few subtle changes in your environment:
One, there is the lightest smell of sulphur in the air - a memory of a match being struck.
Two, there is a sizable chance that this might be a volcanic vent tube.
Three, as long as your are remembering correctly, all you see near that glimpse of 
reflection you had early is a minor outcropping and shard of rock"""

		}

verbose[19] = {
	"short":"Desending stairwell.",
	"long":
"""While on the steps, a small rumble and shake of the earth
makes your pulse race yet again today. However, the moment is quick and fleeting - the
mountain only sneezed.

As evidenced by the amount of dust just kicked up from the passageway you had used earlier.

You have a strong suspicion that the only way out is now foreward."""

		}

verbose[20] = {
	"short":"Northern Hall",
	"long":
"""Why call it the Northern Hall? Well... besides being basically empty, dusty, full of cobwebs
(that's still empty!), and hewn from the mountain itself - the very last step down into the room
has a rather ornate script chisels into it which reads:

	'Northern Hall'"""

		}

verbose[21] = {
	"short":"Southern Hall",
	"long":
"""Yet another oddity of apparent engineering, after checking the various doors, the entrance
to the SouthWestern Hallway reffuses to reopen due to some unknown locking mechanism,
having heard that that telltale click and thud when the door sealed.

Otherwise, the room is effectively the mirror image of the Northern Hall. Steps leading downward at the
northern end of the room, and a door leading back into the quartercircle hallway system circling the center."""

		}

verbose[22] = {
	"short":"Western Hall",
	"long":
"""The doors in this underground domain seem to be uniquely engineered, as you distintly heard an odd
click and thus when you last heard the door from the NorthWest Hallway close.

This room, however, reminds you of a third quarter moon - almost a half circle, abut against what you might
assume to be the North Hall - east of you?

(Confused yet? I'm your guide and I'm bloody lost. Too bad I dropped my wineskin climbing down that
mountain...)"""

		}

verbose[23] = {
	"short":"Eastern Hall",
	"long":
"""The clicks and thuds of the doors occasionally self sealing is now anticipated - but still
aggrivating. As the Western Hall reminded you of a third quarter moon, this room is reminiscant of
the first quarter moon.

Or maybe half a cake.

When -was- the last time we ate, boss?"""

		}

verbose[24] = {
	"short":"NorthWestern Hallway",
	"long":
"""Apparently the engineers here loved to label things. First the Northern Hall, and now the Northwestern
Hallway. Unimaginative as all, though. Those doors make odd sounds when the close though...

Well, unimaginative in name alone. The hallway here is basically the upperleft quarter of a circle... rounding the center
rooms and a door heading out."""

		}

verbose[25] = {
	"short":"NorthEastern Hallway",
	"long":
"""A long curved hallway carved into the middle of a mountain. The doors keep on clicking and latching in
strange ways, the rooms are each named with stylized script chiseled into the floor.

Oh and to top it all off there is a goldbar on the floor at the northernmost end of the hallway.

(Someone let me know when we get back to 'Normal')"""

		}

verbose[26] = {
	"short":"SouthWestern Hallway",
	"long":
"""The circle apparently continues with this corridor. Doors at both ends, but no
promises made whether they open back up after we use them. On the plus side, we're
who knows how far underground and yet it seems like the air is fresh. I would call that
a good sign..."""

		}

verbose[27] = {
	"short":"SouthEastern Hallway",
	"long":
"""Sure, another stairwell headed deeper into this labyrinth in the other room. Why don't
we stick around and see how well we can get lost?

Oh wait. We are, aren't we?"""

		}

verbose[28] = {
	"short":"Even more steps...",
	"long":
"""I swear on all that is holy, if we start seeing fire and brimstone I'm quintupling my
rates as a guide. There's stairs. They go back up to that round weirdness upstairs, but
I'm betting we won't go that way since there was that pesky little cave-in some time ago.

Waitasecond....
Cave.

I smell fresher air here. I think thats even natural light coming in from the North!"""

		}

verbose[29] = {
	"short":"Cave entrance.",
	"long":
"""The glare from natural sunlight mutes even your now overly pessimistic guide for a moment.

The silence is nice, for a change.

Taking in the view, you see a river spreading far as your vision will allow. Apparently the rapids once
heard while hanging upside down over a chasm may very well be downstream from here. The current is lax, and
nature has provided a bit of shallows for an easy ford across.

However, if the desire strikes, those same shallows can be followed along the river to the east or the west."""

		}

verbose[30] = {
	"short":"River ford.",
	"long":
"""As anticipated, fording the river seems to be an unchallenging experience. However, blocking your way is
a behemoth of a man, clad in green from head to toe, standing ankle deep in the water directly across from you.

As strange as that sight may be, your gaze is drawn behind the giant - a few steps behind him rests the edge of
a drawbridge. Behind that drawbridge lies the most extravagant castle (fortress?) carved into the cliff face. Bas reflief
of wings, swords, and divine light adorn the battlements - while statuary (which, to scale, make the Green Man look tiny)
guard the open gates."""

		}

verbose[31] = {
	"short":"Western River",
	"long":
"""Gentle current, fresh breeze... and a giant castle in the rock of the other shore. What's not to enjoy?"""

		}

verbose[32] = {
	"short":"Western River",
	"long":
"""That's a bi-ii-ig castle. Again, the walk is pleasant - even if you have to get your feet wet here and there.
The river continues to wind to the west from here, and continues to flow east from your position."""

		}

verbose[33] = {
	"short":"Western River",
	"long":
"""After countless curves in the meandering river, the castle is out of sight.

However, glancing away from the reflection of the light while looking east, you see what
may very well be the biggest clam you've ever set eyes on."""

		}

verbose[34] = {
	"short":"Eastern River",
	"long":
"""Following the current and the breeze, the river continues to wind through this impressive
ravine. Oh, and there's still a mind boggling castle carved into the mountain on the other side.

Little things. Nothing to worry or ponder about."""

		}

verbose[35] = {
	"short":"Eastern River",
	"long":
"""Much more meandering of the river and you may not be sure if it is still flowing east.

Away from that castle.

Um, boss? Castle?"""
		}

verbose[36] = {
	"short":"Eastern River",
	"long":
"""Indeed, we cannot see the castle from here. We do have a wonderful view of a twisting
chasm/ravine/whatever you want to call it...

But I'll bet we won't have to worry about any earthquakes in a castle, right boss?

Right?"""

		}

verbose[37] = {
	"short":"Staring down a drawbridge.",
	"long":
"""...
...
...
That's one big, freaking, drawbridge, boss.
And that statuary, I think they were carved out of the rockface the same time the
castle was. Seamless work.

Literally.

(Shall we go in? We got the ok. Well, Close enough to count.)"""

		}

verbose[38] = {
	"short":"Standing upon a rather spectacular drawbridge.",
	"long":
"""Pardon my enamorment with their architecture, boss... It just seems that
there would have been teams upon teams of draft horses to raise or lower
that monstrosity.

Looking anywhere near the edge of the drawbridge does offer a tinge
of vertigo to the viewer. Apparently these lands have chasms to the deepest depths
right alongside skycapped mountains.

The bas-relief and statuary does keep the eye from wandering down, at least."""
		}

verbose[39] = {
	"short":"The Grand Royal Hall (formerly known as)",
	"long":
"""To even the uninformed eye, this room would have been the center of
any event. Any wood has aged and rotten away, the tapestries are mere
streaks of mold and mildew, and the chandeliers have all chashed and shattered
into dust.

To the east, the Royal Dais is directly viewable.
Directly, yet obscured... for some internal portcullis bars your
way to the throne."""
		}

verbose[40] = {
	"short":"The Royal Dais",
	"long":
"""Even with the decay of the area, you can still capture a feeling
of the most robust reds and purples decorating the area... signifying
the highest of the high, and possibly the most righteous of the right.

The visions of past grandiose fade when you realize that a bare skeleton
rests on the sole throne."""
		}

verbose[41] = {
	"short":"The Master Bedroom",
	"long":
"""Furnishings in this room are noticable merely by the general sizes of rot and
dust and faded fabric scraps.

Apparently fortune seekers have made their way here before you some time ago,
for you can see where portraits once adorned the walls...
...yet the floor has an undisturbed layer of dust that can only form
with ample amounts of time."""
		}

verbose[42] = {
	"short":"What once was most likely a linen closet...",
	"long":
"""Most likely to be a linen closet is in reality most definitely a rats nest now.
Multiple squeaks and scurrying sounds come from under broken pieces of wood
and fabric remnants."""
		}

verbose[43] = {
	"short":"Something a cross between a sitting area and a serving area....",
	"long":
"""The layout of the room is reminiscent of a parlor used for tea, but the
abject lack of anything that decrees royalty seems to imply this room was
a source of comfort for those who were a lower station than the ruling family.

The thoughts of finding valuables in a royal castle seem to be flitting away
faster and faster with each passing puff of dust underfoot."""
		}

verbose[44] = {
	"short":"Shall we call it a 'Leisure Room'?",
	"long":
"""Seriously, boss. We're just going to keep it at that. Everything's all run down
and all, but the remnants of a wood frame over in the corner remind me of somthing
which I would not wish to mention in public."""


		}

verbose[45] = {
	"short":"A side room. Undiscript, really.",
	"long":
"""Undiscript and untouched for ages.

And apparently engineered by the same people who did the
interesting sealing/locking doors in the garrison(?) under the
mountain.

No promises, boss... but I have the sneaking suspicion many
of these doors are going to be one-way-only here also..."""
		}

verbose[46] = {
	"short":"A broken down lavatory.",
	"long":
"""Well, it was a lavatory at some time. Possibly outfitted with
ivory and marble, and garnished with brass and gold.

Nowadays, the furnishings have disintegrated and any material of
value has been in the purview of others for a long, long time."""
		}

verbose[47] = {
	"short":"Pedestal Garden",
	"long":
"""In truth, it was once to be a statuary garden.

The only thing that stands now are the pedestals which
once supported the statues - and on display for aeons to
and audience of dust."""
		}

verbose[48] = {
	"short":"...what once may have been a lavish kitchen...",
	"long":
"""What once may have been a lavish kitchen has been scavenged
down to the flagstone underfoot. It would be a challenge to find
something made of metal in this room... let alone something of value."""
		}

verbose[49] = {
	"short":"The private (royal?) loungue.",
	"long": 
"""Just like the rest of the castle, just about anything of value
or furnishing has deteriorated or disappeared. This room is the exception
apparently - two stone thrones (apparently a His & Hers matched set, Boss)
are built into the wall.

For stone, they might even had been comfortable... with some cloth and pillows."""

		}

verbose[50] = {
	"short":"Guard station",
	"long":
"""How do I know it's a guard station, boss?

Quite simply, there is a wear pattern on the floor that all but
screams that heavily armored feet frequented this room often.

However, what is more interesting about the floor is what looks
to be a loose piece of flagstone almost revealing something
hidden underneath."""
		}

verbose[51] = {
	"short":"Royal Vault",
	"long":
"""One.
Big.
Empty.
Vault.

C'mon Boss, there's got to be some-thing...."""
		}

verbose[52] = {
	"short":"Grand Dining Room",
	"long":
"""Again, it was probably called 'Grand' some age ago. Now it is
only grand in physical size and volume... and a grand mess of empty &
boring.

And I was exited to explore a castle. Apparently that's why you are the
boss... Boss."""
		}

verbose[53] = {
	"short":"Guest bedroom",
	"long":
"""Apparently this room had less use and traffic than the others. This
room has less of a film of dust and spiderwebs, and you can almost still
make out what would have been the bedframe showcased against the wall.

"""
		}

verbose[54] = {
	"short":"The Bath.",
	"long":
"""

"""
		}

verbose[55] = {
	"short":"...to be completely honest, boss...\nI don't know what to call this room\nThere's a big hookah in here though...",
	"long":
"""Sure, the metal parts have rusted away into nothingness... but that blown glass
was said to be a very popular design for royalty ages ago. Apparently the salesperson
I spoke to back in the day DID know what they were talking about.

But yeah, Hookah room..."""
		}

verbose[56] = {
	"short":"...what may have been a wine display area...",
	"long":
"""...is now a minefield of broken bottles a glass - punctuated by the
random sighting of a cork amongst the shrapnel. The wooden stands have
folded up against themselves - unable to stand against the pressing weight
of time."""
		}

verbose[57] = {
	"short":"a dilapidated storage area",
	"long":
"""The only remaining hint that this was a storage area are the shelves carved
directly into the wall.

Adorning these shelves is a liberal coating of dust
and the tracks of a mouse over said coating."""

		}

verbose[58] = {
	"short":"Stewards area.",
	"long":
"""I don't know what happened here boss, but I'm not sure it was innocent.
This room was charred from the inside out, and I'm positive that there is no
damage in any of the adjoining rooms we have seen."""
		}

verbose[59] = {
	"short":"Sitting room",
	"long":
"""A lone stone stool sits in the middle of the room - carved into the floor.
That's as good as reason as any to call this room the Sitting Room."""

		}

verbose[60] = {
	"short":"Side Room",
	"long":
"""This room just feels... stale. You almost hear the sound of air escaping
when the door opened. Run down and destroyed, nothing of value seems to remain
anywhere around.

It is only when you drop your gaze to the floor in exasperation that you
notice a keyhole hidden into the floor. Odd."""
		}

verbose[61] = {
	"short":"The Darkness",
	"long":
"""



There's nowhere to go but...

"""
		}


# ITEMS AND ITEMS AND ITEMS

items = {"letter" : "(Reading the letter:)\nInspired by all the hours sitting in front of a Commodore 64...\nplaying Zork from a Five and a Quarter floppy disk.\nP.S. Never be afraid to as for 'help'.", \
	"pocketlint":"Because you expected to start out playing with a ton of stuff, perhaps?", \
	"woodenstake":"Solid, even with a little bit of char remaining. It does taper to a rather decent point, however.", \
	"rope":"A supple reminder that heights really aren't your thing. Rope is a great security blanket against the threat of gravity.",\
	"pinecone":"Maybe save it for some wreath or festive cheer come winter?", \
	"quartz":"A smoky rose crystal, once encased in a protective shell by nature - defaced by you.", \
	"turquoise":"A little dusty and waterstained, but with a light polish it should show some life again.", \
	"obsidian":"A hand sided chunk of obsidian, unpolished on the outside - smooth and sharp as broken glass on the fresh edge.\nYou try hard to not thing about the fact that obsidian tends to be near volcanic activity.", \
	"torch":"No. You are not carrying this in your pocked. However, the waxy tar'ish substance feeding the flame does not seem to diminish much as all as you watch the flames dance in front of you.", \
	"goldbar":"Yup, it's still gold. Yup, it's still heavy. Nope, you're probably not sharing.", \

	}

#give intro
giveintro = intro()

#room overview/debug
num = 0
while num < len(world):
	#print (world[num])
	num += 1

print (verbose[location]["short"])

#maxscore
for num in range (0, len(world)):
	#print(world[num]["points"])
	score += world[num]["points"]
	#print(score)
score += 35 #doublecheck this from override enounters
#print(score)

while done == False:
	location, inventory, done, movescount, movesfail, points = actions(world, verbose, location, movement, extras, inventory, items, movescount, movesfail, points)

movescount, movesfail, score, points = endgame(movescount, movesfail, score, points)	

